### ISSUE TITLE
getting makefiles for /apps/projective_space and similar

### ISSUE THREAD

**Issue by robertosussex** [abetten/orbiter#27]
Hi there,

I am trying to recompile orbiter and related binaries on a Centos 7 machine however I cant seem to be able to  find makefiles to compile the directories

algebra  codes          graph_theory   makefile  projective_space  solver           surfaces
arcs     combinatorics  groups         orbiter   regular_ls        spread           test
blt      ginac          linear_spaces  packing   semifield         subspace_orbits  tools

Any idea where I can find them ?

Many thanks

Roberto Scipioni
MPS Research Computing Support
University of Sussex, UK

**Comment by abetten** [comment]
Hi Roberto,

the directories apps/projective space etc have been removed with the exceptions of apps/orbiter which contains the command line interface. 

Is there any need to get anything from these old directories going? I could create new command line interfaces for things that are desired but no longer available. 

Most of the stuff from apps in available through the command line interface, and the documentation is available (users guide).

Are you using the most recent version or are you trying to compile an old version?

Best, Anton

**Comment by robertosussex** [comment]
Thanks!
A researcher here is trying to use binaries like
src/apps/projective_space/canonical_form.out
which are MAC binaries and obviously do not work on Linux. Any advice ?

Many thanks


Roberto


________________________________

**Comment by abetten** [comment]
Oh, you are in luck. All of the canonical form stuff is now available through the command line interface. You should get hold of the most recent version of the user's guide through. Let me do a push. Please check out the doc directory in a couple of minutes. Best, Anton

**Comment by abetten** [comment]
OK I pushed it.

**Comment by robertosussex** [comment]
Thanks!
R.
________________________________

**Comment by robertosussex** [comment]
So if I understand correctly I need to read the user documentation ? Where do I find it ?
R.

**Comment by robertosussex** [comment]
I would need to replace a  command like

~/orbiter3/src/apps/projective_space/canonical_form.out -v 2 -n 2 -q 7 -input -file_of_points  ......

with something like

.../bin/orbiter.out .....

is that the idea ?

R.

________________________________

**Comment by abetten** [comment]
Yes, exactly!

Could you do one more git pull? I had to correct a few small errors.

Please check out doc/users_guide.pdf
and 
examples/users_guide/makefile

type make EC, for instance.

This is the example in the users guide, section 10.

You should get a group of order 6.

**Comment by robertosussex** [comment]
Could I use a git clone to some address ?
R.
________________________________

**Comment by abetten** [comment]
Yes, of course! That is how it is supposed to start. Got pull is only to update. Please see the user's guide. A.
