### ISSUE TITLE
Choosing a license

### ISSUE THREAD

**Issue by alex-konovalov** [abetten/orbiter#33]
@abetten could you please specify under which license this software package is distributed? A good practice would be to provide a plain text file `LICENSE` (without extension) with the license text, and mention the type of the license, and refer to this file, in the README and documentation.

https://choosealicense.com/ may be a helpful place to start, if you yet have to decide.

**Comment by abetten** [comment]
I have selected the GPLv3 license. Thank you for your request.

**Comment by alex-konovalov** [comment]
Thanks for the quick response! Here is how I discovered this: https://twitter.com/gap_system/status/1288888171766468609

**Comment by abetten** [comment]
Nice! Thanks for letting me know.
